### ISSUE TITLE
unparsable Go source: expected '}', found 'type' 

### ISSUE THREAD

**Issue by danwt** [idodod/protoc-gen-fieldmask#46]
I've built and installed the tool. Then using buf:

```yaml
# buf.gen.yaml
# Generated by "buf config migrate-v1beta1". Edit as necessary, and
# remove this comment when you're finished.
version: v1
plugins:
  - name: go
    out: .
    opt: paths=source_relative
  - name: go-grpc
    out: .
    opt: paths=source_relative
  - name: fieldmask
    out: .
```

And running

```bash
✗ buf generate -o pkg/proto
Failure: plugin fieldmask: github.com/<repo>/../<filename>.pb.fieldmask.go: unparsable Go source: 296:1: expected '}', found 'type' (and 9 more errors)
```

I'm sorry I can't provide a narrower concrete example right now.
